//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IS_FootballClub.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class MatchResults
    {
        public int ID_Match { get; set; }
        public int ID_Team { get; set; }
        public int Score { get; set; }
        public string EnemyTeam { get; set; }
        public int EnemyScore { get; set; }
        public string Id_Result { get; set; }
    
        public virtual Match Match { get; set; }
        public virtual Results Results { get; set; }
        public virtual Teams Teams { get; set; }
    }
}
