//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IS_FootballClub.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FootballClubEntities : DbContext
    {
        public FootballClubEntities()
            : base("name=FootballClubEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Groups> Groups { get; set; }
        public virtual DbSet<Match> Match { get; set; }
        public virtual DbSet<MatchResults> MatchResults { get; set; }
        public virtual DbSet<Players> Players { get; set; }
        public virtual DbSet<Results> Results { get; set; }
        public virtual DbSet<Roles> Roles { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<TeamPlayers> TeamPlayers { get; set; }
        public virtual DbSet<Teams> Teams { get; set; }
        public virtual DbSet<Trainers> Trainers { get; set; }
        public virtual DbSet<Users> Users { get; set; }
    }
}
