//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IS_FootballClub.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Players
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Players()
        {
            this.TeamPlayers = new HashSet<TeamPlayers>();
        }
    
        public int ID_Player { get; set; }
        public string Id_Group { get; set; }
        public string Id_Role { get; set; }
        public string Name { get; set; }
        public string LastName { get; set; }
        public int PlayerNumber { get; set; }
        public System.DateTime DateOfBirth { get; set; }
        public System.DateTime JoinDate { get; set; }
    
        public virtual Groups Groups { get; set; }
        public virtual Roles Roles { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TeamPlayers> TeamPlayers { get; set; }
    }
}
