//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IS_FootballClub.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TeamPlayers
    {
        public int ID_Team { get; set; }
        public int ID_Player { get; set; }
        public Nullable<System.DateTime> JoinDate { get; set; }
    
        public virtual Players Players { get; set; }
        public virtual Teams Teams { get; set; }
    }
}
